
import { Navbar } from "@/components";
import "../../public/css/global.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="back-image">
          <div className="pt-4 px-space-between-navbar">
            <Navbar/>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
